#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

printf "\e[?1049h"
clear

echo -e ""
echo -e "     \e[3mBerzelius\e[m"
echo -e "    by Tina_lel   \n"

mkdir -p "$DIRMAIN/calls"
mkdir -p "$DIRMAIN/tmp"

# FUNCTIONS
CHAT_GET() {
	socat -u tcp:$HOST:$OPORT - | gpg -q -d -o "$DIRMAIN/tmp/main" --cipher-algo AES256 --batch --yes --passphrase $PASS -
	clear
	cat "$DIRMAIN/tmp/main"
	rm "$DIRMAIN/tmp/main"
	printf " --> "
}
CHAT_GET_FILE() {
	socat -u tcp:$HOST:$OPORT - | gpg -q -d -o "$DIRMAIN/tmp/main" --cipher-algo AES256 --batch --yes --passphrase $PASS -
}
WAIT_LOOP() {
	while :
	do
		socat tcp:$HOST:$COMPORT,forever - || break
		CHAT_GET
		sleep 1
	done &
	LOOP_PID=$!
}
EXITER() {
	killall "socat" > /dev/null 2>&1
	kill $LOOP_PID
	printf "\e[?1049l"
	exit
}

# TRAPS
trap "EXITER" SIGINT

echo -e "Enter encryption password for $HOST"
echo -e -n "\e[1;32mPassword >>\e[m "
read -s -r -e PASS

WAIT_LOOP
CHAT_GET
while :
do
	read -r -e MSG
	case $MSG in
	!exit)
		EXITER
	;;
	!scroll)
		killall "socat" > /dev/null 2>&1
		kill $LOOP_PID
		CHAT_GET_FILE
		less $DIRMAIN/tmp/main
		WAIT_LOOP
		CHAT_GET
	;;
	!help)
		killall "socat" > /dev/null 2>&1
		kill $LOOP_PID
		clear
		echo -e "\n List of commands:"
		echo -e " -----------------"
		echo -e " !help: show this message"
		echo -e " !scroll: view chat history"
		echo -e " !exit: exit and disconnect"
		echo -e " -----------------\n"
		echo -e -n " Press Enter to return."
		read
		WAIT_LOOP
		CHAT_GET
	;;
	*)
		echo -e -n " Sending... "
		echo "$NAME: $MSG" | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
	;;
	esac
done
