#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config

printf "\e[?1049h"
clear

mkdir -p "$DIRMAIN/tmp"

# FUNCTIONS
CHAT_GET() {
	socat -u tcp:$HOST:$OPORT - | gpg -q -d -o "$DIRMAIN/tmp/main" --cipher-algo AES256 --batch --yes --passphrase $PASS -
	clear
	cat "$DIRMAIN/tmp/main" | xargs --null echo -e
	rm "$DIRMAIN/tmp/main"
}
WAIT_LOOP() {
	while :
	do
		socat tcp:$HOST:$COMPORT,forever - || break
		CHAT_GET
		sleep 1.25
	done &
	LOOP_PID=$!
}
JOIN_MESSAGE() {
	echo " >> \e[3mUser $NAME_COLOR$NAME\e[m\e[3m has joined the chat\e[m << " | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
}
LEAVE_MESSAGE() {
	echo " << \e[3mUser $NAME_COLOR$NAME\e[m\e[3m has left the chat\e[m >> " | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
}
LOGO() {
	echo -e ""
	echo -e "     \e[1;35mBerzelius\e[m"
	echo -e "    by Tina_lel   \n"
}
CONTROLS_HELP() {
	printf "\e[s"
	printf "\e[9999;0H"
	printf "\e[7;32m| $UP: up | $DOWN: down | $QUIT: quit |\e[m"
	printf "\e[u"
}
SOFT_EXITER() {
	printf "\e[?1049l"
	exit
}
EXITER() {
	LEAVE_MESSAGE
	killall "socat" > /dev/null 2>&1
	kill $LOOP_PID
	printf "\e[?1049l"
	exit
}

# ctrl+c trap ONLY FOR THE SELECTION PART
trap "SOFT_EXITER" SIGINT

LOGO

echo -e "What server to join?"
while :
do
	FUNCS_NUMBER="$(echo ${FUNCS[@]} | wc -w)"
	NUMLOL=0
	echo ""
	printf "\e[s"
	while [[ $NUMLOL < $FUNCS_NUMBER ]]
	do
		echo -e "${FUNCS[$NUMLOL]}"
		NUMLOL=$(( $NUMLOL + 1 ))
	done
	printf "\e[u"
	CURRENT_LINE=0
	printf "\e[2K\e[100D > \e[7;32m ${FUNCS[$CURRENT_LINE]} \e[m"
	CONTROLS_HELP
	while :
	do
		read -n 1 -s SELECTION_INPUT
		case $SELECTION_INPUT in
		$UP)
			if [[ $CURRENT_LINE == 0 ]]
			then
				continue
			else
				printf "\e[2K\e[100D${FUNCS[$CURRENT_LINE]}"
				printf "\e[A"
				CURRENT_LINE=$(( $CURRENT_LINE - 1 ))
				printf "\e[2K\e[100D > \e[7;32m ${FUNCS[$CURRENT_LINE]} \e[m"
			fi
		;;
		$DOWN)
			if [[ $CURRENT_LINE == $(( $FUNCS_NUMBER - 1 )) ]]
			then
				continue
			else
				printf "\e[2K\e[100D${FUNCS[$CURRENT_LINE]}"
				printf "\n"
				CURRENT_LINE=$(( $CURRENT_LINE + 1 ))
				printf "\e[2K\e[100D > \e[7;32m ${FUNCS[$CURRENT_LINE]} \e[m"
			fi
		;;
		$QUIT)
			SOFT_EXITER
		;;
		"")
			break
		;;
		*)
		;;
		esac
	done

	${FUNCS[$CURRENT_LINE]}

	clear
	LOGO

	echo -e "Enter encryption password for $HOST"
	echo -e -n "\e[1;32mPassword >>\e[m "
	read -s -r -e PASS

	# ctrl+c trap ONLY FOR THE CHAT PART
	trap "EXITER" SIGINT
	JOIN_MESSAGE
	WAIT_LOOP
	while :
	do
		read -r -e MSG
		case $MSG in
		!quit | !q)
			EXITER
		;;
		!back | !b)
			clear
			LEAVE_MESSAGE
			killall "socat" > /dev/null 2>&1
			kill $LOOP_PID
			LOGO
			break
		;;
		!scroll | !s)
			echo -e "Press \"q\" to enable scrolling." | less
			CHAT_GET
		;;
		!help | !h)
			killall "socat" > /dev/null 2>&1
			kill $LOOP_PID
			clear
			echo -e "\n List of commands:"
			echo -e " -----------------"
			echo -e " \"!help\"	| \"!h\" (show this message)"
			echo -e " \"!scroll\"	| \"!s\" (view chat history)"
			echo -e " \"!back\"	| \"!b\" (disconnect and return)"
			echo -e " \"!quit\"	| \"!q\" (disconnect and exit)"
			echo -e " -----------------\n"
			echo -e -n " Press Enter to return."
			read
			WAIT_LOOP
			CHAT_GET
		;;
		*)
			echo -e -n "Sending... "
			while :
			do
				echo "$NAME_COLOR$NAME\e[m: $MSG" | gpg -c --cipher-algo AES256 --batch --yes --passphrase $PASS - | socat -U tcp:$HOST:$IPORT -
				SOCAT_FAIL="$?"
				if [[ $SOCAT_FAIL != 0 ]];
				then
					sleep 0.25
					return
				else
					break
				fi
			done
		;;
		esac
	done
done
